package co.grandcircus.ApiCapstoneRecipe.entity;

public enum HealthLabel {
	
	ALCHOLOL_FREE, CELERY_FREE, CRUSTACEAN_FREE, DAIRY_FREE, EGG_FREE, FISH_FREE,
	GLUTEN_FREE, KETO_FREINDLY, KIDNEY_FRIENDLY, KOSHER, LOW_POTASSIUM, MUSTARD_FREE, NO_OIL_ADDED,
	LOW_SUGAR, PALEO, PEANUT_FREE, PESCATARIAN, PORK_FREE, RED_MEAT_FREE, SESAME_FREE, SHELLFISH_FREE,
	SOY_FREE, SUGAR_CONCIOUS, TREE_NUT_FREE, VEGAN, VEGETARIAN, WHEAT_FREE
	

}
